
warnings: true
compress:
  dead_code: true
  unused: true
  arguments: false
  booleans: false
  collapse_vars: false
  comparisons: false
  conditionals: false
  hoist_funs: false
  hoist_props: false
  hoist_vars: false
  if_return: false
  inline: false
  join_vars: false
  keep_fnames: true
  loops: false
  negate_iife: false
  reduce_funcs: false
  reduce_vars: false
  switches: false
  typeofs: false
  properties: false
  sequences: false
  side_effects: false
  drop_debugger: false
  global_defs:
    DEBUG: false
mangle: false
parse: {}
output:
  beautify: true
  braces: true
  quote_style: 1
  indent_level: 2
  comments: "^!"
