apps:
  autoreload:
    file: src/autoreload/ModuleReload.ts
    outputMain: lib/plugin.reload.js
    package:
      moduleWrapperCustomPath: "./src/autoreload/wrapper.js"
    middlewares:
      js:
      - atma-io-middleware-condcomments:read
      - atma-io-middleware-importer:read
  browser-default:
    outputMain: lib/mask.js
    package:
      moduleWrapperCustomPath: "./src/umd-wrapper.js"
    settings:
      atma-io-middleware-condcomments:
        defines:
          BROWSER: true
      atma-io-middleware-uglify:
        uglify:
          warnings: true
          compress:
            dead_code: true
            unused: true
            arguments: false
            booleans: false
            collapse_vars: false
            comparisons: false
            conditionals: false
            hoist_funs: false
            hoist_props: false
            hoist_vars: false
            if_return: false
            inline: false
            join_vars: false
            keep_fnames: true
            loops: false
            negate_iife: false
            reduce_funcs: false
            reduce_vars: false
            switches: false
            typeofs: false
            properties: false
            sequences: false
            side_effects: false
            drop_debugger: false
            global_defs:
              DEBUG: false
          mangle: false
          parse: {}
          output:
            beautify: true
            braces: true
            quote_style: 1
            indent_level: 2
            comments: "^!"
    copyFiles:
      ref-mask-node/lib/mask.bootstrap.js: lib/mask.bootstrap.js
      ref-mask-node/lib/mask.node.js: lib/mask.node.js
common:
  file: src/mask.ts
  package:
    module: import
    moduleWrapper: custom
    import:
      removeUnusedExports: true
      lazy:
        "/custom/*":
        - modules/exports
        - expression/exports
        "/builder/*":
        - "/feature/"
        "/renderer/*":
        - compo/exports
        "/mask-compo/*":
        - util/reporters
        - parser/exports
        - builder/exports
        - expression/exports
        - renderer/exports
        - parser/exports
        - "/feature/"
        CompoStatics\b:
        - Component
        "/expression/*":
        - mask-compo
  dynamicDependencies:
  - "^vm$"
  - "^fs$"
  - "^module$"
  - "^path$"
  extensions:
    io:
      type: js
  defaultExtensions:
    js: ts
  middlewares:
    js:
    - atma-io-middleware-condcomments:read
    - atma-io-middleware-importer:read
    - atma-io-middleware-uglify:write
    ts:
    - atma-io-middleware-condcomments:read
    - atma-io-middleware-importer:read
    - atma-loader-ts:read
  options:
    include:
      routes:
        "@core": src/{0}
        "@utils": ref-utils/src/{0}
        "@mask-j": projects/mask-j/src/jmask/{0}
        "@compo": projects/mask-compo/src/{0}
        "@binding": projects/mask-binding/src/{0}
        "@project": projects/{0}
